# Copyright 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

version: "2"

run:
  build-tags:
    - testing

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - zerologlint
    - godoclint
    - whitespace
  settings:
    godoclint:
      enable:
        - start-with-name
        - deprecated
    whitespace:
      multi-if: true
      multi-func: true

formatters:
  settings:
    gci: {}
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
    gofumpt: {}
    goimports: {}
    golines: {}


