# Copyright 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

version: "2"

run:
  build-tags:
    - testing

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - govet
    - gocyclo
    - ineffassign
    - intrange
    - lll
    - staticcheck
    - unused
    - zerologlint
    - godoclint
    - whitespace

  settings:
    cyclop:
      max-complexity: 30
      package-average: 10
    errcheck:
      check-type-assertions: true
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
    funlen:
      lines: 100
      statements: 50
      ignore-comments: true
    gocognit:
      min-complexity: 20
    godoclint:
      enable:
        - start-with-name
        - deprecated
    lll:
      line-length: 140
      tab-width: 1
    whitespace:
      multi-if: true
      multi-func: false

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - bodyclose
          - dupl
          - funlen
          - goconst
          - gosec
          - noctx
          - wrapcheck
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-same-issues: 50

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      no-inline-comments: true
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
    gofumpt: {}
    goimports: {}
    golines:
      max-len: 140
      tab-len: 1