# Copyright 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

version: "2"

run:
  build-tags:
    - testing

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - zerologlint

formatters:
  settings:
    gci: {}
    gofmt:
      simplify: true
    gofumpt: {}
    goimports: {}
    golines: {}


