# Copyright 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: Go Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.12-dind
        ports:
          - 5701:5701
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod

      - name: Run go test
        run: go test -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./... -tags=testing -p=1
